In [7]:
!pip list

Package                                  Version
---------------------------------------- -------------------
absl-py                                  1.4.0
accelerate                               1.13.0
access                                   1.1.10.post3
affine                                   2.4.0
aiofiles                                 24.1.0
aiohappyeyeballs                         2.6.1
aiohttp                                  3.13.5
aiosignal                                1.4.0
aiosqlite                                0.22.1
alabaster                                1.0.0
albucore                                 0.0.24
albumentations                           2.0.8
ale-py                                   0.11.2
alembic                                  1.18.4
altair                                   5.5.0
annotated-doc                            0.0.4
annotated-types                          0.7.0
antlr4-python3-runtime                   4.9.3
anyio                         

In [8]:
import numpy as np

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([[1,2,3],[4,5,6]])

print(arr1)
print(arr2)
print()
print(arr1.shape)   # 1차원 (5,)
print(arr2.shape)   # 2차원 (2,3)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]

(5,)
(2, 3)


In [9]:
# 난수 이용한 2차원 배열
# randn : random normal distribution (정규분포)
# 정규분포인가? normal, 정규, 가우시안(Gaussian)
np.random.randn(3)

array([-0.45621226,  0.10556529,  0.47826195])

In [10]:
arr3 = np.random.randn(3)
arr4 = np.random.randn(2,3)

print(arr3)
print()
print(arr4)

[1.12722298 0.17817904 0.97605338]

[[-1.62572367  0.50045311  1.346694  ]
 [-0.13475823  0.37151234  1.55715902]]


In [11]:
# 원소를 0또는 1로 초기화

arr5 = np.zeros(5)
arr6 = np.ones((2,3))

print(arr5)
print()
print(arr6)

[0. 0. 0. 0. 0.]

[[1. 1. 1.]
 [1. 1. 1.]]


In [12]:
# arange()와 reshape()  ***중요
# arange() : array+range
# arange(start, end, step)

arr7 = np.arange(20, 200, 10)

print(arr7)
print(arr7.shape)
print(len(arr7))

[ 20  30  40  50  60  70  80  90 100 110 120 130 140 150 160 170 180 190]
(18,)
18


In [13]:
# 반드시 알아야 해!! (변환)
arr7.reshape(3, -1)

array([[ 20,  30,  40,  50,  60,  70],
       [ 80,  90, 100, 110, 120, 130],
       [140, 150, 160, 170, 180, 190]])

In [14]:
arr8 = arr7.reshape(3, -1)
arr8

array([[ 20,  30,  40,  50,  60,  70],
       [ 80,  90, 100, 110, 120, 130],
       [140, 150, 160, 170, 180, 190]])

In [15]:
# 배열 다루기
ar1= np.arange(1,21,1)
print(ar1[1])

2


In [16]:
len(ar1)

20

In [17]:
ar2 = ar1.reshape(2,-1)
ar2

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [18]:
ar2[1]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [19]:
ar2[1][1]

np.int64(12)

In [20]:
ar2[1][4]

np.int64(15)

In [21]:
# 값 변경 / 추출
ar2[1][1] = 100
print(ar2[1][1])

100


In [22]:
ar2

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11, 100,  13,  14,  15,  16,  17,  18,  19,  20]])

In [23]:
print(ar2[0])
print(ar2[1])
print(ar2[0][-1])

[ 1  2  3  4  5  6  7  8  9 10]
[ 11 100  13  14  15  16  17  18  19  20]
10


In [24]:
# 배열의 산술연산: 배열의 연산은 배열 원소에 각각 적용된다

ar1 = np.arange(1,11,1)
ar2 = ar1 + 3   # broadcasting(각 원소에 적용)
ar3 = ar1 * 3

print(ar1)
print()
print(ar2)
print()
print(ar3)
print()

[ 1  2  3  4  5  6  7  8  9 10]

[ 4  5  6  7  8  9 10 11 12 13]

[ 3  6  9 12 15 18 21 24 27 30]



In [25]:
# 배열의 통계 메소드 이용
arr = np.array([[5,7,9],[-7,-6,19],[6,9,11]])

print(arr)
print(arr.sum())    # 전체 요소의 합
print(arr.mean())
print(arr.max())
print(arr.min())
print(arr.argmax()) # 배열에서 가장 큰 값을 가진 인덱스

[[ 5  7  9]
 [-7 -6 19]
 [ 6  9 11]]
53
5.888888888888889
19
-7
5


In [26]:
print(arr.max(axis=0))
print(arr.max(axis=1))

[ 6  9 19]
[ 9 19 11]


In [27]:
# 조건식 사용한 연산
arr

array([[ 5,  7,  9],
       [-7, -6, 19],
       [ 6,  9, 11]])

In [28]:
arr>0

array([[ True,  True,  True],
       [False, False,  True],
       [ True,  True,  True]])

In [29]:
# 실무에서
condition = (arr > 0)

In [30]:
condition.sum()

np.int64(7)

In [31]:
# np.where
# -> SQL에서 유래(Select/From/Where)
# -> Where: 조건

# arr < 0 조건식
# 조건식이 참(True) (arr < 0) >>> 0 반환, 아니면 arr 출력

np.where(arr<0, 0, arr)

array([[ 5,  7,  9],
       [ 0,  0, 19],
       [ 6,  9, 11]])

In [32]:
arr

array([[ 5,  7,  9],
       [-7, -6, 19],
       [ 6,  9, 11]])

In [33]:
arr.sort(0)
# axis = 0 열단위로 원소를 정렬

In [34]:
arr

array([[-7, -6,  9],
       [ 5,  7, 11],
       [ 6,  9, 19]])

In [35]:
arr.sort(1)
# axis = 1 행단위로 원소를 정렬

In [36]:
arr

array([[-7, -6,  9],
       [ 5,  7, 11],
       [ 6,  9, 19]])

In [37]:
# np.sort() vs arr.sort() 차이 : 원본 수정 여부

import numpy as np

arr10 = np.array([3, 1, 4, 5, 2, 1, 5, 3, 4])
print(arr10)

[3 1 4 5 2 1 5 3 4]


In [38]:
np.sort(arr10)  # 원본 변경 없음 (default: 오름차순)

array([1, 1, 2, 3, 3, 4, 4, 5, 5])

In [39]:
arr10

array([3, 1, 4, 5, 2, 1, 5, 3, 4])

In [40]:
arr10.sort()    # 원본 변경됨 (default: 오름차순)
arr10

array([1, 1, 2, 3, 3, 4, 4, 5, 5])

In [41]:
# argsort() : 정렬된 인덱스
arr11 = np.array([30, 10, 40, 20])
print(arr11)

[30 10 40 20]


In [42]:
np.argsort(arr11)
# 순서 맞춰줄 때 사용

array([1, 3, 0, 2])

In [43]:
# eos