In [3]:
import numpy as np

# numpy 의 부동소수점 자리수 표시
np.set_printoptions(suppress=True, precision=3)

In [4]:
np.array([1,2,3,4,5,6])

array([1, 2, 3, 4, 5, 6])

In [5]:
n1 = np.array([1,2,3,4,5,6])
print(n1)

[1 2 3 4 5 6]


In [6]:
# 요소수 확인
print(n1.shape) # 1차원

(6,)


In [7]:
len(n1)

6

In [8]:
np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [10,11,12]
])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [9]:
n2 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

print(n2)
print(n2.shape)
# (4, 3)
# 4행 3열, 4개의 배열, 각 배열 3개의 원소가 있어요. 원소 개수 12

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)


In [10]:
print(len(n2))

4


In [11]:
import numpy as np
n1 = np.array([1,2,3,4,5,6])
print(n1)
print(n1.shape)
print(len(n1))

[1 2 3 4 5 6]
(6,)
6


In [12]:
n2 = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [10,11,12]
])
print(n2)
print(n2.shape)
print(len(n2))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)
4


zeros, ones 함수 이용

In [13]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [14]:
n3 = np.zeros(5)
print(n3.shape) # 1차원

(5,)


In [15]:
np.ones(3)

array([1., 1., 1.])

In [16]:
np.ones((2,3))
# np.ones(2,3)
# TypeError 발생

array([[1., 1., 1.],
       [1., 1., 1.]])

In [17]:
n4 = np.ones((2,3))
print(n4)
print(n4.shape)

[[1. 1. 1.]
 [1. 1. 1.]]
(2, 3)


In [18]:
# 모든 요소 정규분포를 따르는 변수와 3개 행렬
np.random.randn(2,3,4)
# random : 무작위, 임의적 >> 일반화
# randn(normalize) >> 정규분포 평균 0, 표준편차 1
# 표준화 (x-x_bar) / sigma
# >> x : 원래 값, x_bar 평균 sigma 편차
# 정규화 (x-x_min) / (x_max - x_min) >> [0,1]
# // x_max-x_min -> 실제 데이터 범위
# >> x: 원래 값, x_min: 해당 속성(열) 최소값, x_max: 해당 속성(열) 최대값
# n으로 나눈다 n = len(x)
# (2,3,4) : 3개의 배열, 각 배열마다 4개의 원소를 가지고 있는 행렬이 2개

array([[[-1.424, -0.601,  0.803,  0.918],
        [ 1.245,  1.813, -0.116, -0.829],
        [ 0.009, -0.03 , -1.066,  0.002]],

       [[ 0.086, -0.239, -1.638, -0.368],
        [ 1.368,  1.527, -0.325,  0.009],
        [ 1.494,  0.519, -2.379, -1.404]]])

In [19]:
n5 = np.random.randn(2,3,4)
print(n5.shape)

(2, 3, 4)


그래프 출력용 수치 배열 생성

In [20]:
np.linspace(-1,1,11)

array([-1. , -0.8, -0.6, -0.4, -0.2,  0. ,  0.2,  0.4,  0.6,  0.8,  1. ])

In [21]:
n6 = np.linspace(-1,1,11)
print(n6.shape)

(11,)


In [22]:
n6.ndim
# ndim : number of dimension 차원 수

1

In [23]:
np.arange(-1, 1.2, 0.2)

array([-1. , -0.8, -0.6, -0.4, -0.2, -0. ,  0.2,  0.4,  0.6,  0.8,  1. ])

조작 (manupulation)

In [24]:
# 특정 행, 열 추출
print(n2)
print(n2.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)


In [25]:
n2[:, 0]

array([ 1,  4,  7, 10])

In [26]:
n2[:,0].shape
# 차원 이동(2차원->1차원)

(4,)

In [27]:
np.array([False, True,False, True])

array([False,  True, False,  True])

In [28]:
n7 = np.array([False, True, False, True])
n2[n7] # 마스크 추출

array([[ 4,  5,  6],
       [10, 11, 12]])

In [29]:
n2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [30]:
n8 = n2[n7]
n8.shape

(2, 3)

reshape(**)

In [31]:
print(list(range(24)))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]


In [32]:
# 초기 변수 1개 배열
np.array(range(24))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [33]:
n9 = np.array(range(24))
n9.shape

(24,)

In [34]:
n9.reshape(3,8)     # 원소의 개수를 맞춰줘야 함.

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [35]:
n9.reshape(3, -1)   # -1 : 자동으로 맞춰줌.
# 3개의 배열 만들고 전체 원소 개수 고려해서 마지막 열에 맞춰 만들어줘.

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [36]:
n9.reshape(8, -1)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [37]:
n9.reshape(-1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [38]:
# n9.reshape(9,-1)
# ValueError 개수를 맞춰줘야 함.

In [39]:
n9.reshape(2,2,-1)
# 3차원

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]],

       [[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]])

In [40]:
n9.reshape(2,2,2,-1)
# 4차원

array([[[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]],


       [[[12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23]]]])

In [41]:
# n9.reshape(3, 9)
# ValueError: cannot reshape array of size 24 into shape (3,9)

In [42]:
# -1 을 지정, 자동 계산
n9.reshape(2,-1, 3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

In [43]:
n9.reshape(2,4, 3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

축 교체하기

In [44]:
print(n2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [45]:
# 전치 행렬(행과 열 바꿔주는 것, 위치를 바꾸다)
# T : transpose
n2.T

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [46]:
n9

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [47]:
n9.reshape(2, -1, 4)
# 3차원

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [48]:
n10 = n9.reshape(2, -1, 4)
n10.shape

(2, 3, 4)

In [49]:
np.transpose(n10)

array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])

In [50]:
np.transpose(n10).shape

(4, 3, 2)

In [52]:
n10.shape

(2, 3, 4)

In [53]:
np.transpose(n10, (1,2,0))
# (1, 2, 0)
# 변환 위치 지정
# 기존 0번 축 => 2번 축
# 기존 1번 축 => 0번 축
# 기존 2번 축 => 1번 축

array([[[ 0, 12],
        [ 1, 13],
        [ 2, 14],
        [ 3, 15]],

       [[ 4, 16],
        [ 5, 17],
        [ 6, 18],
        [ 7, 19]],

       [[ 8, 20],
        [ 9, 21],
        [10, 22],
        [11, 23]]])

In [54]:
np.transpose(n10, (1,2,0)).shape

(3, 4, 2)

In [55]:
np.transpose(n10, (2,1,0))

array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])

In [56]:
one_d = np.array([1,2,3,4,5])
one_d

array([1, 2, 3, 4, 5])

In [57]:
one_d.shape # 1차원

(5,)

In [58]:
one_d.T

array([1, 2, 3, 4, 5])

In [59]:
two_d = np.reshape(one_d, (5,1))
two_d

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [60]:
two_d.shape # 2차원

(5, 1)

In [61]:
two_d.T

array([[1, 2, 3, 4, 5]])

In [62]:
two_d.T.shape

(1, 5)

행렬 연결하기

In [63]:
np.array(range(1,7))

array([1, 2, 3, 4, 5, 6])

In [64]:
np.array(range(1,7)).reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [65]:
# 2행 3열 행렬
n13 = np.array(range(1,7)).reshape(2,3)
n14 = np.array(range(7,13)).reshape(2,3)

In [66]:
n13

array([[1, 2, 3],
       [4, 5, 6]])

In [67]:
n14

array([[ 7,  8,  9],
       [10, 11, 12]])

In [68]:
# 3요소 벡터
n15 = np.array(range(14, 17))
n15

array([14, 15, 16])

In [69]:
# 행렬과 행렬 연결 (n13, n14)
# vstack vertically stack 수직으로 쌓아줘
np.vstack([n13, n14])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [70]:
np.hstack([n13,n14])
# hstack horizontally stack 수평으로 쌓아줘

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [71]:
np.concatenate([n13,n14])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [101]:
np.concatenate([n13,n14], axis=0)
# np.concat([n13,n14], axis=0)

# axis=0 (default 기본설정)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [73]:
np.concatenate([n13,n14], axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [74]:
np.concat([n13,n14], axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [75]:
# n1 = np.arange(1, 7).reshape(2,3)
# n2 = np.arange(8, 14).reshape(2,3)
# print(np.vstack([n1, n2]))
# print(np.hstack([n1, n2]))

In [76]:
# print(np.concatenate([n1, n2], axis=0))
# print(np.concatenate([n1, n2], axis=1))

연산

In [77]:
# 넘파이 변수끼리 연산
# 원본
print(n13)
print(n14)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [78]:
n13 + n14

array([[ 8, 10, 12],
       [14, 16, 18]])

In [79]:
n15 = n13 + n14
n15

array([[ 8, 10, 12],
       [14, 16, 18]])

브로드캐스팅

In [80]:
print(n1)

[1 2 3 4 5 6]


In [81]:
# 모든 요소에서 같은 값을 빼고 싶어요
n1 - 3

array([-2, -1,  0,  1,  2,  3])

유니버설 함수

In [82]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [83]:
np.linspace(0, 2*np.pi, 5)

array([0.   , 1.571, 3.142, 4.712, 6.283])

In [84]:
x = np.linspace(0, 2*np.pi, 5)
y = np.sin(x)
print(y)

[ 0.  1.  0. -1. -0.]


집계함수

In [85]:
n1

array([1, 2, 3, 4, 5, 6])

In [86]:
np.sum(n1)

np.int64(21)

In [87]:
np.mean(n1)

np.float64(3.5)

In [88]:
np.max(n1)

np.int64(6)

In [89]:
np.min(n1)

np.int64(1)

응용예시

In [90]:
# 두 변수를 비교해서 일치하는 개수로 정확도 계산

# 2개의 넘파이 배열 준비

# 정답
yt = np.array([1,1,0,1,0,1,1,0,1,0])

# 예측
yp = np.array([1,1,0,1,0,1,0,1,1,1])

In [91]:
# 정답(yt)과 예측(yp) 잘 맞나? (비교)

(yt == yp)

array([ True,  True,  True,  True,  True,  True, False, False,  True,
       False])

In [92]:
matched = (yt == yp)
matched.sum()

np.int64(7)

In [93]:
# 맞은 개수(정답 수 세는 방법)
correct = matched.sum()

# 전체 수
total = len(matched)

# 정확도 계산
accuracy = correct / total
print(accuracy)

0.7


In [94]:
print(f'정답수: {correct}, 전체 개수: {total}, 정확도: {accuracy*100}%')

정답수: 7, 전체 개수: 10, 정확도: 70.0%


벡터 값을 1차 함수로 변환 [0,1] 범위로 제한

In [95]:
# 모든 값을 [0,1] 범위에 포함하도록 변환하고 싶어요
n1

array([1, 2, 3, 4, 5, 6])

In [96]:
n1_max = n1.max()
n1_min = n1.min()
print(n1_max, n1_min)

6 1


In [97]:
# 변환(정규화 공식)
(n1 - n1_min) / (n1_max - n1_min)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])