# CNN(Convolution Neural Network)

![ezgif com-animated-gif-maker](https://github.com/user-attachments/assets/f726212f-95f6-4408-9cc4-62da36c38086)

출처: https://www.youtube.com/watch?v=pj9-rr1wDhM&t=336s

* 이미지 인식 분야에서 특히 뛰어나며, 입력 데이터를 여러 레이어 거치면서 특징을 추출하고 학습하여 객체 인식, 분류 등에 활용
* CNN 모델의 기본적인 구성: 합성곱 레이어(Convolution layer), 풀링(Pooling), fully-connected layer(분류기에서 사용됨)
* 합성곱 레이어의 학습 파라메터: 필터(커널)



## Convolution Filter (Kernel): 합성곱 신경망이 학습하는 파라메터

![image](https://github.com/user-attachments/assets/1203400f-92ee-4561-995b-a48c42007178)
- 계산식: 0 * 0 + (-1) * 0 + 0 * 0 + 0 * (-1) + 60 * 5 + 113 * (-1) + 0 * 0 + 73 * (-1) + 121 * 0 = 114

출처: https://medium.com/@Suraj_Yadav/in-depth-knowledge-of-convolutional-neural-networks-b4bfff8145ab

![1_O06nY1U7zoP4vE5AZEnxKA](https://github.com/user-attachments/assets/7238bdaa-65ad-458a-84a7-b16ab8a4362e)

출처: https://medium.com/@Suraj_Yadav/in-depth-knowledge-of-convolutional-neural-networks-b4bfff8145ab

## Stride: 이동할 칸 수

![1_Bmx3AHBhx0D5OmBSxtY6gw](https://github.com/user-attachments/assets/868b19c8-62c3-4b2b-94c2-4b472445924f)

![1_X22-wmPcir4y5VoeqDyvWg](https://github.com/user-attachments/assets/a1df99ea-096f-438b-b997-caa935f72010)

출처: https://medium.com/@Suraj_Yadav/in-depth-knowledge-of-convolutional-neural-networks-b4bfff8145ab

## Zero-padding: 이미지 입력이나 특징맵의 테두리에 0을 덧붙임
 - 목적: 가장자리 정보 손실 방지, 특징맵 크기 유지

![image](https://github.com/user-attachments/assets/c1548757-cf97-4d55-ae81-e18b937a344a)

![image](https://github.com/user-attachments/assets/081a29da-9095-4438-a58f-66607485631b)


## Convolution 연산 과정

* 필터(커널)의 채널 수는 입력 채널 수와 같아야 함
* 아래 그림에서 필터 하나가 총 3개의 채널로 구성된 것임. (필터가 3개인 것이 아니다.)

![image](https://github.com/user-attachments/assets/d7b4f327-d128-4da9-ac59-fe5f131acd5a)

* 필터의 각 채널은 입력 이미지의 각 채널과 대응되어 합성곱 연산을 진행

![image](https://github.com/user-attachments/assets/52666246-3017-4a8d-9b3d-6ea72099f2ae)

<!-- ![image](https://github.com/user-attachments/assets/34e38a4e-25d8-4ca0-acf7-aeb8b9d3ab47) -->

![image](https://github.com/user-attachments/assets/8cd429d8-a56f-4aeb-be34-6a463731a77a)

<!-- ![image](https://github.com/user-attachments/assets/a15a033c-3f74-47c1-81c8-99ad75609f2a) -->

<!-- ![image](https://github.com/user-attachments/assets/8706cd10-4600-42d7-9445-5740a2ecd93d) -->

![image](https://github.com/user-attachments/assets/71dd5e03-5794-4ff5-bcae-f92d71c6d537)

![image](https://github.com/user-attachments/assets/971729ad-002e-4864-bd61-c3ac59c70ec9)

![image](https://github.com/user-attachments/assets/f96372d8-a96d-45c4-bb34-d4aaf74314c3)

* 출력 특징맵의 차원은 합성곱 필터의 개수와 같음


출처: https://dev.to/sandeepbalachandran/machine-learning-convolution-with-color-images-2p41

## 출력 특징맵 크기 계산 식

![image.png](attachment:image.png)

![image-2.png](attachment:image-2.png)

출처: https://woochan-autobiography.tistory.com/884

## CNN 예제 - nn.Conv2d

In [13]:
import torch

cnn1 = torch.nn.Conv2d(2, 3, kernel_size=4, stride=1, padding=1)

'''
* Conv2d arguments: (input_channel, output_channel, kernel_size, stride, padding)
* 그 외 인자: dilation=1, groups=1, bias=True, padding_mode='zeros', device=None, dtype=None
* 자세한 사항은 https://docs.pytorch.org/docs/stable/generated/torch.nn.Conv2d.html 참고
'''

# cnn의 weight와 bias 선언
cnn1.weight.data = torch.randint(low=1, high=5, size=(3, 2, 2, 2), dtype=torch.int).float() # cnn의 weight shape은 (output_dim, input_dim, kernel_size, kernel_size) 순임.
cnn1.bias.data = torch.tensor([1,2,3]).float() # cnn의 bias shape은 output_dim 이랑 같음.

# 무작위 입력 생성
input = torch.randint(low=0, high=3, size=(2, 5, 5), dtype=torch.int).float()
print("입력 텐서: ", input)

# TO-DO: 입력의 shape 확인하기
print(input.shape)

print("=" * 100)

# TO-DO: cnn의 weight와 bias 확인하기
print(cnn1.weight)
print(cnn1.bias)

print("=" * 100)

# TO-DO: cnn의 weight와 bias의 shape 확인하기
print(cnn1.weight.shape)
print(cnn1.bias.shape)

print("=" * 100)

# TO-DO: cnn1 layer의 출력과 그 shape 확인하기
output = cnn1(input)
print(output)
print(output.shape)

print("=" * 100)

입력 텐서:  tensor([[[1., 1., 2., 0., 0.],
         [2., 1., 0., 2., 1.],
         [0., 0., 0., 0., 1.],
         [0., 2., 1., 0., 0.],
         [0., 1., 0., 2., 2.]],

        [[2., 0., 2., 1., 2.],
         [1., 2., 0., 0., 0.],
         [1., 1., 0., 2., 2.],
         [2., 1., 1., 1., 2.],
         [1., 2., 0., 2., 0.]]])
torch.Size([2, 5, 5])
Parameter containing:
tensor([[[[2., 3.],
          [3., 4.]],

         [[1., 2.],
          [2., 4.]]],


        [[[4., 3.],
          [2., 4.]],

         [[3., 1.],
          [3., 2.]]],


        [[[4., 3.],
          [3., 1.]],

         [[4., 2.],
          [1., 3.]]]], requires_grad=True)
Parameter containing:
tensor([1., 2., 3.], requires_grad=True)
torch.Size([3, 2, 2, 2])
torch.Size([3])
tensor([[[13., 12., 20., 15., 11.,  5.],
         [20., 28., 20., 17., 16.,  6.],
         [13., 19.,  7., 15., 24., 10.],
         [11., 20., 18., 14., 20.,  9.],
         [ 9., 25., 18., 22., 24.,  9.],
         [ 3.,  9.,  5., 11., 13.,  5.]],

     

## CNN의 장점

Convolutional Layer(CNN 레이어)는 Fully Connected(FC) Layer에 비해 몇 가지 중요한 장점이 있습니다. 이러한 장점은 CNN이 특히 이미지 데이터에서 뛰어난 성능을 발휘하게 하는 요인입니다.

### 1. 공간적 관계 유지
> **FC Layer**: 모든 입력 뉴런이 모든 출력 뉴런에 연결되므로 입력의 공간적 구조가 무시됩니다. 따라서 FC Layer는 입력 데이터의 공간적 관계를 인식할 수 없습니다.

> **Convolution Layer**: 입력 이미지의 작은 영역(리셉티브 필드)에 대해서만 필터를 적용합니다. 이로 인해 CNN은 인접 픽셀 간의 관계를 유지하고 학습할 수 있으며, 이미지의 공간적 패턴을 인식하는 데 유리합니다.

### 2. 파라미터 수 감소
> **FC Layer**: 입력과 출력의 모든 뉴런이 연결되므로, 입력 크기와 출력 크기에 따라 파라미터 수가 급격히 증가합니다.

> **Convolution Layer**: 동일한 필터를 이미지 전체에 걸쳐 적용하므로, 파라미터 수가 크게 줄어듭니다. 이는 파라미터 공유(parameter sharing)로 인해 가능하며, 모델이 더 효율적이고 메모리 절약적입니다.

### 3. 변환 불변성(Translation Invariance)
> **FC Layer**: 입력 데이터의 위치 변화에 민감하여, 데이터의 이동이나 왜곡에 취약합니다.

> **Convolution Layer**: 필터가 이미지의 모든 위치에 동일하게 적용되기 때문에, 객체의 위치 변화에 대해 비교적 강인합니다. 이는 이미지 내 객체의 위치가 약간 변해도 그 특징을 잘 인식할 수 있게 합니다.

# Pooling
* 풀링의 목적: 특징 맵의 크기 감소, 계산 효율성 증대, 오버피팅 방지

![image.png](attachment:image.png)

## Max Pooling
* 특징맵에서 가장 두드러지는 특징을 찾도록 한다.

In [2]:
input = torch.tensor([[[12 , 20 , 30, 0 ],
                       [8  , 12 , 2 , 0 ],
                       [34 , 70 , 37, 4 ],
                       [112, 100, 25, 12]]])

MaxPool = torch.nn.MaxPool2d(kernel_size=2, stride=2, padding=0)
Output = MaxPool(input)
print(Output)

tensor([[[ 20,  30],
         [112,  37]]])


## Average Pooling
* 전체적인 정보를 보존하면서 특징맵 크기 줄일 때 사용

In [3]:
input = torch.tensor([[[12 , 20 , 30, 0 ],
                       [8  , 12 , 2 , 0 ],
                       [34 , 70 , 37, 4 ],
                       [112, 100, 25, 12]]])

AvgPool = torch.nn.AvgPool2d(kernel_size=2, stride=2, padding=0)
Output = AvgPool(input)
print(Output)

tensor([[[13,  8],
         [79, 19]]])


# CNN 예제 - MNIST 데이터 학습

## MNIST

![image](https://github.com/user-attachments/assets/0873d1cb-0645-4598-9ba1-d39d2e35953e)

In [4]:
import torch
import torch.nn as nn
import torch.optim as optim
import torchvision
import torchvision.transforms as transforms
from torch.utils.data import DataLoader

# dataset 전처리
transform = transforms.Compose([
    transforms.ToTensor(),  # 이미지를 Tensor로 변환
    transforms.Normalize((0.5,), (0.5,))  # 정규화: 평균 0.5, 표준편차 0.5로 스케일링
])

# MNIST dataset 다운로드 및 로드
train_dataset = torchvision.datasets.MNIST(root='./data', train=True, download=True, transform=transform)
test_dataset = torchvision.datasets.MNIST(root='./data', train=False, download=False, transform=transform)

100%|██████████| 9.91M/9.91M [00:00<00:00, 19.9MB/s]
100%|██████████| 28.9k/28.9k [00:00<00:00, 479kB/s]
100%|██████████| 1.65M/1.65M [00:00<00:00, 4.48MB/s]
100%|██████████| 4.54k/4.54k [00:00<00:00, 14.7MB/s]


In [14]:
# 훈련 데이터셋의 첫번째 데이터 정보 출력
train_dataset[0]


(tensor([[[-1.0000, -1.0000, -1.0000, -1.0000, -1.0000, -1.0000, -1.0000,
           -1.0000, -1.0000, -1.0000, -1.0000, -1.0000, -1.0000, -1.0000,
           -1.0000, -1.0000, -1.0000, -1.0000, -1.0000, -1.0000, -1.0000,
           -1.0000, -1.0000, -1.0000, -1.0000, -1.0000, -1.0000, -1.0000],
          [-1.0000, -1.0000, -1.0000, -1.0000, -1.0000, -1.0000, -1.0000,
           -1.0000, -1.0000, -1.0000, -1.0000, -1.0000, -1.0000, -1.0000,
           -1.0000, -1.0000, -1.0000, -1.0000, -1.0000, -1.0000, -1.0000,
           -1.0000, -1.0000, -1.0000, -1.0000, -1.0000, -1.0000, -1.0000],
          [-1.0000, -1.0000, -1.0000, -1.0000, -1.0000, -1.0000, -1.0000,
           -1.0000, -1.0000, -1.0000, -1.0000, -1.0000, -1.0000, -1.0000,
           -1.0000, -1.0000, -1.0000, -1.0000, -1.0000, -1.0000, -1.0000,
           -1.0000, -1.0000, -1.0000, -1.0000, -1.0000, -1.0000, -1.0000],
          [-1.0000, -1.0000, -1.0000, -1.0000, -1.0000, -1.0000, -1.0000,
           -1.0000, -1.0000, -1.000

In [15]:
# 첫번째 훈련 데이터의 이미지 shape 출력
train_dataset[0][0].shape

torch.Size([1, 28, 28])

In [16]:
# DataLoader를 사용하여 데이터 배치 처리
train_loader = DataLoader(train_dataset, batch_size=128, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=128, shuffle=False)

In [31]:
# CNN 모델 정의
class SimpleCNN(nn.Module):
    def __init__(self):
        super().__init__()
        # 첫 번째 Convolution layer: 입력 채널 1개, 출력 채널 32개, 커널 크기 3x3, stride=1, padding=1
        self.conv1 = nn.Conv2d(1, 32, kernel_size=3, stride=1, padding=1)
        # MaxPooling layer: 2x2 풀링
        self.pool = nn.MaxPool2d(kernel_size=2, stride=2, padding=0)
        # 두 번째 Convolution layer: 입력 채널 32개, 출력 채널 64개, 커널 크기 3x3
        self.conv2 = nn.Conv2d(32, 64, kernel_size=3, stride=1, padding=1)
        # fc-lyaer 1: 64채널 7x7 이미지 -> 128개의 출력
        self.fc1 = nn.Linear(64 * 7 * 7, 128)
        # fc-lyaer 2: 128개의 출력 -> 10개의 클래스 (0-9 숫자)
        self.fc2 = nn.Linear(128, 10)
        # nn.ReLU() 활성화 함수를 self.relu로 저장
        self.relu = nn.ReLU(inplace=True)
        # 벡터로 평탄화 시키는 nn.Flatten()을 self.flatten으로 저장
        self.flatten = nn.Flatten()

        self.features = nn.Sequential(
            self.conv1, self.relu, self.pool,
            self.conv2, self.relu, self.pool
        )

        self.classifier = nn.Sequential(
            self.fc1, self.relu, self.fc2
        )

    def forward(self, x):
        x = self.features(x)
        x = self.flatten(x)
        x = self.classifier(x)
        # # TO-DO: 첫 번째 convolution layer -> ReLU -> Max pooling
        # x = self.conv1(x)
        # x = self.relu(x)
        # x = self.pool(x)    # 크기: [8, 32, 14, 14]

        # # TO-DO: 두 번째 convolution layer -> ReLU -> Max pooling
        # x = self.conv2(x)
        # x = self.relu(x)
        # x = self.pool(x)    # 크기: [8, 64, 7, 7]

        # # TO-DO: view 함수로 특징맵을 1차원으로 펼치기(위 init에서 self.flatten도 사용 가능)
        # x = self.flatten(x) # 크기: [8, 64 * 7 * 7]

        # # TO-DO: 첫 번째 fc-layer -> ReLU
        # x = self.fc1(x)
        # x = self.relu(x)    # 크기: [8, 128]

        # # TO-DO: 두 번째 fc-layer -> 최종 logit 출력
        # x = self.fc2(x)     # 크기: [8, 10]

        return x

# device 저장. gpu 사용 가능하면 gpu로 설정.
device = ("cuda:0" if torch.cuda.is_available() else 'cpu')

# 모델 인스턴스 생성
model = SimpleCNN().to(device)

# 손실 함수 및 옵티마이저 정의
criterion = nn.CrossEntropyLoss()  # 교차 엔트로피 손실 함수
optimizer = optim.Adam(model.parameters(), lr=0.001)  # Adam 옵티마이저 사용, 학습률 0.001

# Epoch 수 결정
epochs = 10

In [32]:
# 모델 정보 summary 출력
import torchsummary

torchsummary.summary(model,(1, 28, 28))

----------------------------------------------------------------
        Layer (type)               Output Shape         Param #
            Conv2d-1           [-1, 32, 28, 28]             320
            Conv2d-2           [-1, 32, 28, 28]             320
              ReLU-3           [-1, 32, 28, 28]               0
              ReLU-4           [-1, 32, 28, 28]               0
              ReLU-5           [-1, 32, 28, 28]               0
         MaxPool2d-6           [-1, 32, 14, 14]               0
         MaxPool2d-7           [-1, 32, 14, 14]               0
            Conv2d-8           [-1, 64, 14, 14]          18,496
            Conv2d-9           [-1, 64, 14, 14]          18,496
             ReLU-10           [-1, 64, 14, 14]               0
             ReLU-11           [-1, 64, 14, 14]               0
             ReLU-12           [-1, 64, 14, 14]               0
        MaxPool2d-13             [-1, 64, 7, 7]               0
        MaxPool2d-14             [-1, 6

In [19]:
# 모델 훈련 함수
def train_model(model, train_loader, criterion, optimizer, num_epochs):
    # 지정된 epoch 수만큼 반복
    for epoch in range(num_epochs):
        running_loss = 0.0
        # 데이터 배치 단위로 반복
        for images, labels in train_loader:
            images, labels = images.to(device), labels.to(device) # 입력과 정답의 device를 gpu로 변환
            optimizer.zero_grad()  # optimizer의 기울기 초기화
            outputs = model(images)  # 모델의 예측값 계산 (Batch_size, 10)
            loss = criterion(outputs, labels)  # 손실 계산
            loss.backward()  # backpropagation을 통해 기울기 계산
            optimizer.step()  # 가중치 업데이트

            running_loss += loss.item()

        # epoch당 평균 손실 출력
        print(f'Epoch [{epoch+1}/{num_epochs}], Loss: {running_loss/len(train_loader):.4f}')

# 모델 평가 함수 정의
def evaluate_model(model, test_loader):
    model.eval()
    correct = 0
    total = 0
    with torch.no_grad():
        for images, labels in test_loader:
            images, labels = images.to(device), labels.to(device) # 입력과 정답의 device를 gpu로 변환
            outputs = model(images) # 모델의 예측값 계산
            _, predicted = torch.max(outputs.data, 1) # 예측한 결과 출력
            total += labels.size(0) # total: test한 총 데이터 개수
            correct += (predicted == labels).sum().item() # 모델이 맞춘 개수 계산

    print(f'\n테스트 정확도: {100 * correct / total:.2f}%')


train_model(model, train_loader, criterion, optimizer, epochs) # 모델 학습시키는 함수 가동하여 모델 학습

evaluate_model(model, test_loader) # 학습된 모델을 테스트하기 위해 평가 함수 실행

Epoch [1/10], Loss: 0.2086
Epoch [2/10], Loss: 0.0557
Epoch [3/10], Loss: 0.0375
Epoch [4/10], Loss: 0.0288
Epoch [5/10], Loss: 0.0219
Epoch [6/10], Loss: 0.0177
Epoch [7/10], Loss: 0.0129
Epoch [8/10], Loss: 0.0112
Epoch [9/10], Loss: 0.0089
Epoch [10/10], Loss: 0.0093

테스트 정확도: 98.84%
